default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 'koding-development'
  
test:
  <<: *default
  database: 'koding-test'

production:
  <<: *default
  database: 'koding'
